# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_delete_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lang',
            field=models.CharField(choices=[('RU', 'Russian'), ('UA', 'Ukrainian')], default='RU', max_length=1),
        ),
    ]
