# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20171122_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='lang',
        ),
    ]
