# Generated by Django 2.0 on 2018-02-08 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('posted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
