# Generated by Django 2.0 on 2018-03-14 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='icon',
            new_name='image',
        ),
    ]
